### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [nim579/node-srv#28]
Hello,

As a member of the [Node.js ecosystem security team](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md) I have been reported a security issue regarding this package.

I have made attempts to contact the person identified as maintainer of this package but did not get any answer.

What is the best way to reach someone with commit rights over this repo in order to privately explain what is the issue and resolve it?

Best, 
Liran Tal.

**Comment by nim579** [comment]
Hi,

I'm an author of this package. Please write me on email dev@nim579.ru.

**Comment by lirantal** [comment]
@nim579 thanks for replying. I already invited you to the HackerOne platform. Did you not get it?

**Comment by nim579** [comment]
@lirantal Sorry, I missed this letter. Now I found it. Thank you!

I slove this issue today.
